






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace EMAAR.ECM.Feature.Navigation.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace EMAAR.ECM.Feature.Navigation.Models.sitecore.templates.Sample
{


 	/// <summary>
	/// ISample_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sample/Sample Item</para>	
	/// <para>ID: 76036f5e-cbce-46d1-af0a-4143f9b557aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample_ItemConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISample_Item : IGlassBase 
	{
								/// <summary>
					/// The Text field.
					/// <para>ここにアイテムのテキストを入力してください</para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: a60acd61-a6db-4182-8329-c957982cec74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample_ItemConstants.TextFieldName)]
					string Text  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para>ここにアイテムのタイトルを入力してください</para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 75577384-3c97-45da-a847-81b00500e250</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample_ItemConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class ISample_ItemConstants{

			public const string TemplateIdString = "76036f5e-cbce-46d1-af0a-4143f9b557aa";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sample Item";

					
			public static readonly ID TextFieldId = new ID("a60acd61-a6db-4182-8329-c957982cec74");
			public const string TextFieldName = "Text";
			
					
			public static readonly ID TitleFieldId = new ID("75577384-3c97-45da-a847-81b00500e250");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Sample_Item
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sample/Sample Item</para>	
	/// <para>ID: 76036f5e-cbce-46d1-af0a-4143f9b557aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample_ItemConstants.TemplateIdString)] //, Cachable = true
	public partial class Sample_Item  : GlassBase, ISample_Item 
	{
	   
						/// <summary>
				/// The Text field.
				/// <para>ここにアイテムのテキストを入力してください</para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: a60acd61-a6db-4182-8329-c957982cec74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample_ItemConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para>ここにアイテムのタイトルを入力してください</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 75577384-3c97-45da-a847-81b00500e250</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample_ItemConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
