






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace EMAAR.ECM.Foundation.ORM.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace EMAAR.ECM.Foundation.ORM.Models.sitecore.templates.Sample
{


 	/// <summary>
	/// ISample_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sample/Sample Item</para>	
	/// <para>ID: 76036f5e-cbce-46d1-af0a-4143f9b557aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample_ItemConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISample_Item : IGlassBase 
	{
								/// <summary>
					/// The Text field.
					/// <para>ここにアイテムのテキストを入力してください</para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: a60acd61-a6db-4182-8329-c957982cec74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample_ItemConstants.TextFieldName)]
					string Text  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para>ここにアイテムのタイトルを入力してください</para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 75577384-3c97-45da-a847-81b00500e250</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample_ItemConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class ISample_ItemConstants{

			public const string TemplateIdString = "76036f5e-cbce-46d1-af0a-4143f9b557aa";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sample Item";

					
			public static readonly ID TextFieldId = new ID("a60acd61-a6db-4182-8329-c957982cec74");
			public const string TextFieldName = "Text";
			
					
			public static readonly ID TitleFieldId = new ID("75577384-3c97-45da-a847-81b00500e250");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Sample_Item
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sample/Sample Item</para>	
	/// <para>ID: 76036f5e-cbce-46d1-af0a-4143f9b557aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample_ItemConstants.TemplateIdString)] //, Cachable = true
	public partial class Sample_Item  : GlassBase, ISample_Item 
	{
	   
						/// <summary>
				/// The Text field.
				/// <para>ここにアイテムのテキストを入力してください</para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: a60acd61-a6db-4182-8329-c957982cec74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample_ItemConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para>ここにアイテムのタイトルを入力してください</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 75577384-3c97-45da-a847-81b00500e250</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample_ItemConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace EMAAR.ECM.Foundation.ORM.Models.sitecore.templates.Feature
{


 	/// <summary>
	/// ITestGlass Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/TestGlass</para>	
	/// <para>ID: a0bc9e43-93d4-4135-b30d-0f54e58d3f22</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITestGlassConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITestGlass : IGlassBase 
	{
								/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 43b91dcc-3382-4473-9844-27a5d1dd73b0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ITestGlassConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 85c09877-1c43-4b80-8785-6f6cff57cf1e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ITestGlassConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class ITestGlassConstants{

			public const string TemplateIdString = "a0bc9e43-93d4-4135-b30d-0f54e58d3f22";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "TestGlass";

					
			public static readonly ID DescriptionFieldId = new ID("43b91dcc-3382-4473-9844-27a5d1dd73b0");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID TitleFieldId = new ID("85c09877-1c43-4b80-8785-6f6cff57cf1e");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// TestGlass
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/TestGlass</para>	
	/// <para>ID: a0bc9e43-93d4-4135-b30d-0f54e58d3f22</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITestGlassConstants.TemplateIdString)] //, Cachable = true
	public partial class TestGlass  : GlassBase, ITestGlass 
	{
	   
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 43b91dcc-3382-4473-9844-27a5d1dd73b0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITestGlassConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 85c09877-1c43-4b80-8785-6f6cff57cf1e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITestGlassConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace EMAAR.ECM.Foundation.ORM.Models.sitecore.templates.Feature
{


 	/// <summary>
	/// ISample2 Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Sample2</para>	
	/// <para>ID: aee95fca-3972-4d1d-bea9-742118956d79</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample2Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISample2 : IGlassBase 
	{
								/// <summary>
					/// The Sample image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 26b26ed4-cd4f-48f4-8621-3ba345c8f10a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample2Constants.Sample_ImageFieldName)]
					Image Sample_Image  {get; set;}
			
								/// <summary>
					/// The Sample Link field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: 06968340-cfa3-4942-ab1b-b099f25152fc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample2Constants.Sample_LinkFieldName)]
					string Sample_Link  {get; set;}
			
								/// <summary>
					/// The SampleName field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: 7fe02d51-3900-44c1-844b-e326652ca68e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISample2Constants.SampleNameFieldName)]
					DateTime SampleName  {get; set;}
			
				}


	public static partial class ISample2Constants{

			public const string TemplateIdString = "aee95fca-3972-4d1d-bea9-742118956d79";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sample2";

					
			public static readonly ID Sample_ImageFieldId = new ID("26b26ed4-cd4f-48f4-8621-3ba345c8f10a");
			public const string Sample_ImageFieldName = "Sample image";
			
					
			public static readonly ID Sample_LinkFieldId = new ID("06968340-cfa3-4942-ab1b-b099f25152fc");
			public const string Sample_LinkFieldName = "Sample Link";
			
					
			public static readonly ID SampleNameFieldId = new ID("7fe02d51-3900-44c1-844b-e326652ca68e");
			public const string SampleNameFieldName = "SampleName";
			
			

	}

	
	/// <summary>
	/// Sample2
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Sample2</para>	
	/// <para>ID: aee95fca-3972-4d1d-bea9-742118956d79</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISample2Constants.TemplateIdString)] //, Cachable = true
	public partial class Sample2  : GlassBase, ISample2 
	{
	   
						/// <summary>
				/// The Sample image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 26b26ed4-cd4f-48f4-8621-3ba345c8f10a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample2Constants.Sample_ImageFieldName)]
				public virtual Image Sample_Image  {get; set;}
					
						/// <summary>
				/// The Sample Link field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: 06968340-cfa3-4942-ab1b-b099f25152fc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample2Constants.Sample_LinkFieldName)]
				public virtual string Sample_Link  {get; set;}
					
						/// <summary>
				/// The SampleName field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 7fe02d51-3900-44c1-844b-e326652ca68e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISample2Constants.SampleNameFieldName)]
				public virtual DateTime SampleName  {get; set;}
					
			
	}
}
